#' @title DATASET_TITLE
#' @description DATASET_DESCRIPTION
#' @format A data frame with 12905 rows and 239 variables:
#' \describe{
#'   \item{\code{COM_ID}}{character COLUMN_DESCRIPTION}
#'   \item{\code{ENTIDAD}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{NOM_ENT}}{character COLUMN_DESCRIPTION}
#'   \item{\code{MUN}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{NOM_MUN}}{character COLUMN_DESCRIPTION}
#'   \item{\code{LOC}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{NOM_LOC}}{character COLUMN_DESCRIPTION}
#'   \item{\code{lon_deg}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{lon_min}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{lon_sec}}{double COLUMN_DESCRIPTION}
#'   \item{\code{lat_deg}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{lat_min}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{lat_sec}}{double COLUMN_DESCRIPTION}
#'   \item{\code{ALTITUD}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{POBTOT}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{POBFEM}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{POBMAS}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_0A2}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_0A2_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_0A2_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_3YMAS}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_3YMAS_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_3YMAS_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_5YMAS}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_5YMAS_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_5YMAS_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_12YMAS}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_12YMAS_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_12YMAS_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_15YMAS}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_15YMAS_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_15YMAS_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_18YMAS}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_18YMAS_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_18YMAS_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_3A5}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_3A5_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_3A5_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_6A11}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_6A11_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_6A11_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_8A14}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_8A14_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_8A14_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_12A14}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_12A14_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_12A14_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_15A17}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_15A17_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_15A17_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_18A24}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_18A24_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_18A24_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_15A49_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_60YMAS}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_60YMAS_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P_60YMAS_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{REL_H_M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{POB0_14}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{POB15_64}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{POB65_MAS}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PROM_HNV}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PNACENT}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PNACENT_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PNACENT_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PNACOE}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PNACOE_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PNACOE_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PRES2015}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PRES2015_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PRES2015_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PRESOE15}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PRESOE15_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PRESOE15_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P3YM_HLI}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P3YM_HLI_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P3YM_HLI_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P3HLINHE}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P3HLINHE_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P3HLINHE_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P3HLI_HE}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P3HLI_HE_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P3HLI_HE_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P5_HLI}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P5_HLI_NHE}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P5_HLI_HE}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PHOG_IND}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{POB_AFRO}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{POB_AFRO_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{POB_AFRO_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCON_DISC}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCDISC_MOT}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCDISC_VIS}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCDISC_LENG}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCDISC_AUD}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCDISC_MOT2}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCDISC_MEN}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCON_LIMI}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCLIM_CSB}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCLIM_VIS}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCLIM_HACO}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCLIM_OAUD}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCLIM_MOT2}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCLIM_RE_CO}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCLIM_PMEN}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PSIND_LIM}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P3A5_NOA}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P3A5_NOA_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P3A5_NOA_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P6A11_NOA}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P6A11_NOAF}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P6A11_NOAM}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P12A14NOA}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P12A14NOAF}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P12A14NOAM}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15A17A}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15A17A_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15A17A_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P18A24A}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P18A24A_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P18A24A_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P8A14AN}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P8A14AN_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P8A14AN_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15YM_AN}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15YM_AN_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15YM_AN_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15YM_SE}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15YM_SE_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15YM_SE_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15PRI_IN}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15PRI_INF}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15PRI_INM}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15PRI_CO}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15PRI_COF}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15PRI_COM}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15SEC_IN}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15SEC_INF}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15SEC_INM}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15SEC_CO}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15SEC_COF}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P15SEC_COM}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P18YM_PB}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P18YM_PB_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P18YM_PB_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{GRAPROES}}{double COLUMN_DESCRIPTION}
#'   \item{\code{GRAPROES_F}}{double COLUMN_DESCRIPTION}
#'   \item{\code{GRAPROES_M}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PEA}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PEA_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PEA_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PE_INAC}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PE_INAC_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PE_INAC_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{POCUPADA}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{POCUPADA_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{POCUPADA_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PDESOCUP}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PDESOCUP_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PDESOCUP_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PSINDER}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PDER_SS}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PDER_IMSS}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PDER_ISTE}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PDER_ISTEE}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PAFIL_PDOM}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PDER_SEGP}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PDER_IMSSB}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PAFIL_IPRIV}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PAFIL_OTRAI}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P12YM_SOLT}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P12YM_CASA}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{P12YM_SEPA}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PCATOLICA}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PRO_CRIEVA}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{POTRAS_REL}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PSIN_RELIG}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{TOTHOG}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{HOGJEF_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{HOGJEF_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{POBHOG}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PHOGJEF_F}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PHOGJEF_M}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VIVTOT}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{TVIVHAB}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{TVIVPAR}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VIVPAR_HAB}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{TVIVPARHAB}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VIVPAR_DES}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VIVPAR_UT}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{OCUPVIVPAR}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{PROM_OCUP}}{double COLUMN_DESCRIPTION}
#'   \item{\code{PRO_OCUP_C}}{double COLUMN_DESCRIPTION}
#'   \item{\code{VPH_PISODT}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_PISOTI}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_1DOR}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_2YMASD}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_1CUART}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_2CUART}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_3YMASC}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_C_ELEC}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_S_ELEC}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_AGUADV}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_AEASP}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_AGUAFV}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_TINACO}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_CISTER}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_EXCSA}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_LETR}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_DRENAJ}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_NODREN}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_C_SERV}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_NDEAED}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_DSADMA}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_NDACMM}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_SNBIEN}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_REFRI}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_LAVAD}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_HMICRO}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_AUTOM}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_MOTO}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_BICI}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_RADIO}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_TV}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_PC}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_TELEF}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_CEL}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_INTER}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_STVP}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_SPMVPI}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_CVJ}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_SINRTV}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_SINLTC}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_SINCINT}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{VPH_SINTIC}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{TAMLOC}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{id_row}}{integer COLUMN_DESCRIPTION}
#'   \item{\code{dec_lon}}{double COLUMN_DESCRIPTION}
#'   \item{\code{dec_lat}}{double COLUMN_DESCRIPTION} 
#'}
#' @details DETAILS
"comunidadescosteras"